### PR TITLE
feat: allow overriding key for select block

### PR DESCRIPTION
**Pull request by Mara-Li**
See #2

### CODE REVIEW

**Comment by blorbb** [comment]
Thank you for the PR! What you added looks good, but I would prefer a different approach.

I was thinking of using a command for using different hotkeys, and rename the toggle to "Use ctrl/cmd-a for select block", instead of having to manually type the hotkey. Then users could disable this option and set a hotkey with the command instead. I don't like manually setting hotkeys by typing it out, the syntax is easy to mess up imo. You can have a look at the 1.0.0 code for having select block as a command.

Not sure if this would actually be better tho, having two places to set a hotkey might be confusing. Lmk if you have other ideas.

**Comment by Mara-Li** [comment]
My version, at last, allow to disable/override it because some user want to set it. 

I think it can be possible (but a little over-hacking) to detect and put the hotkeys directly into the Obsidian settings, like we do in the hotkeys settings. 
I don't know if other plugin introduce it, to be honest.

**Comment by blorbb** [comment]
My bad I didn't explain what I meant properly.

A "command" is one of those things that pops up when you open the command palette (ctrl P by default). They already support adding custom hotkeys.

A new command "Select block" could be added, which does the same thing as the editor extension, but users can add a hotkey and integrate with other things well (e.g. commands can be added to the mobile toolbar).

Instead of giving the command a hotkey of ctrl-a (which causes problems in other contexts), the settings can have a toggle specifically for using ctrl-a for select block, which uses the editor extension to avoid the problems. If you want a different hotkey, you switch this setting off and set a hotkey on the command.

I agree that putting the hotkey selection directly in settings seems a bit hacky, and may have some unintended issues.

Lmk if there's anything else that needs clarification, sorry for not being clearer before.

**Comment by Mara-Li** [comment]
Well, I successfully do a "hotkey" selection, it was complicated to understand how to do it, but I'm happy with the result

**Comment by blorbb** [comment]
Oh whoops didn't see your new commit, looks very nice! Maybe I'll stick with it, I'll have to test it out later to make sure that it doesn't break anything

**Comment by blorbb** [comment]
Sorry about the long wait, I was overseas for a while!

I tested out your hotkey selection, it doesn't seem to have any issues and works great, but I agree that it feels a little too hacky. Especially with generally better support for commands throughout obsidian, I think it would be better to provide a command for custom hotkeys, and change the toggle to enable/disable using ctrl/cmd-a for select block.

If you're still up for it, feel free to add these changes. Otherwise, lmk and I can have a go at this.

Thanks for helping to figure this out 😄

**Comment by Mara-Li** [comment]
I would keep my edit so you can do it yourself!

**Pull request closed without merging**
